name: Build and Test app
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: [macos-latest]
    env:
      XC_VERSION: ${{ '12.4' }}
      XC_PROJECT: ${{ 'Dinklebot/Dinklebot.xcodeproj' }}
      XC_SCHEME: ${{ 'Dinklebot' }}
    steps:
    - name: Select Xcode 12.4
      run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
    - name: Checkout repository
      uses: actions/checkout@v2      
    - name: Testing iOS app
      run: exec ./.github/scripts/test_app.sh
    - name: Build and Test
      run: /usr/bin/xcodebuild test -project "$XC_PROJECT" -list
